### ISSUE TITLE
Remove buggy character from source

### ISSUE THREAD

**Issue by DushyantaDhyani** [iexcloud/pyEX#239]
**Describe the bug**
The following piece of code has the explicit "%2b" character  (probably coming from the API documentation) which leads to failure in requests (works fine after removing the character)

https://github.com/iexcloud/pyEX/blob/02d223b469788e303f8fd0efb5d0edd5437bd0a4/pyEX/stocks/iex.py#L42-L99

**Comment by timkpaine** [comment]
Thanks, this was an old remnant from an example that used a `+`. It is fixed in 0.5.1
