### ISSUE TITLE
API Doc Return Types Dict but actually List

### ISSUE THREAD

**Issue by MrDevDevy** [iexcloud/pyEX#241]
I'm new to Python and this would be my first project, but the API docs show functions returning a dict type. I am seeing lists instead. How could we parse the data like d["low"] for example? I can't get these values in pyEX.stocks.prices.chart

**Comment by timkpaine** [comment]
Chart returns a json list of dicts https://iexcloud.io/docs/api/#historical-prices

but for something like this you might want to use the chartDF pandas wrapper

**Comment by MrDevDevy** [comment]
That got me somewhere. However, when I choose an exact date the response is cut short by dots "..."

![image](https://user-images.githubusercontent.com/29516805/114306282-4fd10a80-9a90-11eb-96c3-9028913b8023.png)

This is what I used 
`df = c.chartDF(TickerSymbol, timeframe="1d", date="20200409")`
`print(df["low"])`

> 
> 
> Chart returns a json list of dicts https://iexcloud.io/docs/api/#historical-prices
> 
> but for something like this you might want to use the chartDF pandas wrapper
> 
> <img alt="Screen Shot 2021-04-10 at 1 56 13 PM" width="681" src="https://user-images.githubusercontent.com/3105306/114279843-9a0caa00-9a04-11eb-9a72-21dff519de94.png">

**Comment by timkpaine** [comment]
Yep that's just how pandas displays in the terminal.

I recommend going through the getting started docs, they should give you a good overview https://pandas.pydata.org/docs/getting_started/index.html
