### ISSUE TITLE
Are typings for Client correct?

### ISSUE THREAD

**Issue by matt-dalton** [iexcloud/pyEX#281]
Perhaps I'm misunderstanding something...

**Describe the bug**
```
import pyEX as iex

client = iex.Client(
            api_token="Tpk_99999, version='sandbox')

return client.exchanges()
```

is valid use of the API (from my understanding), and seems to functionally work fine (i.e. it returns an array of exchanges).

However this gives me a type error (using Pyright)
```
error: Cannot access member "exchanges" for type "Client"
```

whereas if I access `exchanges` directly from the API the types work fine:
```
return iex.exchanges()
```

**To Reproduce**
Steps above

**Expected behavior**
Would expect the same types to be returned for `client.exchanges` as for `iex.exchanges`

Is there a way of workaround/solution?

**Comment by timkpaine** [comment]
I don't see any bugs in this library, perhaps the typing tool does not fully support what python as a language supports

**Comment by matt-dalton** [comment]
Not sure I fully understand - shouldn't the typings given by the library match what the library offers? Does your type tooling give you the correct results in the above case @timkpaine ?
