### ISSUE TITLE
Docs display the wrong type for property primarySisCode Company endpoint (Didn't know where to report)

### ISSUE THREAD

**Issue by dudenamedjune** [iexcloud/pyEX#309]
In the developer api docs the property primarySicCode in the response for Company is incorrect. 

**To Reproduce**
1. Go to https://iexcloud.io/docs/api/#company
2. View the property primarySicCode and the type states string
3. above in the json response it shows an Int
4. run an http request for the endpoint with a symbol that has primarySicCode avalible and property is an Int 

**Expected behavior**
Docs should show the correct type number

**Screenshots**

<img width="954" alt="Screen Shot 2021-07-14 at 9 38 43 PM" src="https://user-images.githubusercontent.com/8673104/125719452-4f1ed815-d5e0-48f4-8bf3-70aae97cb5c0.png">

**Comment by timkpaine** [comment]
thanks will update
