### ISSUE TITLE
Data for only symbol returned when multiple symbols provided.

### ISSUE THREAD

**Issue by sudeep-quantelai** [iexcloud/pyEX#315]
**Describe the bug**
When I use iexTops method to return data for multiple symbols data for only one symbol is returned

**To Reproduce**
```
>>>import pyEX as p
>>> p.iexTops(symbols='AAPL,ADP', token='pk_xxxxxxxx')
[{'symbol': 'AAPL', 'sector': 'electronictechnology', 'securityType': 'cs', 'bidPrice': 0, 'bidSize': 0, 'askPrice': 0, 'askSize': 0, 'lastUpdated': 1627073936595, 'lastSalePrice': 148.33, 'lastSaleSize': 20, 'lastSaleTime': 1627072867728, 'volume': 874700}]
>>> p.iexTops(symbols=['AAPL','ADP'], token='pk_295d03ff747c4c70858ea95010d8dcad')
[{'symbol': 'AAPL', 'sector': 'electronictechnology', 'securityType': 'cs', 'bidPrice': 0, 'bidSize': 0, 'askPrice': 0, 'askSize': 0, 'lastUpdated': 1627073936595, 'lastSalePrice': 148.33, 'lastSaleSize': 20, 'lastSaleTime': 1627072867728, 'volume': 874700}]
```

**Expected behavior**
I expect to see data for all symbols provided. 

**Screenshots**
See the input and output above

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
- Python3.8

**Comment by timkpaine** [comment]
@sudeep-quantelai there's no guarantee that you'll get data back for every symbol, only symbols which have displayed limit orders resting on the book.

**Comment by timkpaine** [comment]
closing as theres no changes to be done here.
