### ISSUE TITLE
Get more information from "Unknown Symbol" error?

### ISSUE THREAD

**Issue by adamklaff** [iexcloud/pyEX#322]
I'm passing in batches of 100 symbols to upcomingDividends, and on occasion one of the symbols isn't found, which throws this error:

pyEX.common.exception.PyEXception: ('Response 404 - ', 'Unknown symbol')

Is there a way for the response to include the offending symbol so I can retry without it? Otherwise I have no way of knowing which of the 100 symbols was problematic.

**Comment by timkpaine** [comment]
There may be, but it has to be implemented upstream in the API, the client just bubbles up whatever errors the server sends
