### ISSUE TITLE
bulkBatchDF returns chart of only first symbol in list

### ISSUE THREAD

**Issue by meaninginuse** [iexcloud/pyEX#34]
Awesome project.

Not sure if this is a limitation of the API or what but successive symbols return no data for 'chart'.

**Comment by timkpaine** [comment]
can you elaborate? I see the expected behavior
<img width="706" alt="screen shot 2018-12-01 at 7 15 17 pm" src="https://user-images.githubusercontent.com/3105306/49334188-7962f880-f59d-11e8-89c6-d9596bf93b9b.png">

**Comment by meaninginuse** [comment]
Sure. I get the error when I don't specify the type. 
eg. pyEX.bulkBatchDF(symbols,_range='1m', last=10)

I get data for all symbols when I specify the type.
pyEX.bulkBatchDF(symbols, types='chart', _range='1m', last=10)

**Comment by timkpaine** [comment]
ah cool thanks for the repro, will take a look

**Comment by timkpaine** [comment]
looks like the API won't give you back more charts unless you request 3 or fewer fields, you can test with [this link](https://api.iextrading.com/1.0/stock/market/batch?symbols=aapl,ibm,jpm&types=book,chart,company,dividends,earnings,financials,stats,news,peers,splits&range=1m&last=10). If you get rid of more `types` you'll get the other chart data when you get down to only 3

**Comment by timkpaine** [comment]
a related issue: https://github.com/iexg/IEX-API/issues/461

**Comment by timkpaine** [comment]
related: https://github.com/iexg/IEX-API/issues/346

**Comment by timkpaine** [comment]
related: https://github.com/iexg/IEX-API/issues/325

**Comment by timkpaine** [comment]
related https://github.com/iexg/IEX-API/issues/156
