### ISSUE TITLE
Stale Data using Client's chartDF & intraday-prices methods 

### ISSUE THREAD

**Issue by carterjfulcher** [iexcloud/pyEX#345]
**Describe the bug**
I've noticed that when making several subsequent calls of  _either_ the `chartDF` or `intradayDF` methods they return stale data. For example, I will call the method once per minute, expecting to see a new row appended to the dataframe upon each iteration. However, the data is stale and is up to date as of the minute I initiated the script. 

**To Reproduce**
Run a script similar to the following: 

```python
import pyEX
from time import sleep

TOKEN = "sk_xxxxxxxxxxxxxxxxxxxx"

client = pyEX.Client(api_token=TOKEN)

while True:
    print(client.chartDF("MU", "dynamic").iloc[-1])
    sleep(60)
```

**Expected behavior**
If I tailed the df and fetched the last row and minute (label), I would expect to see the following: (this was fetched directly from the IEX Cloud API bypassing the pyEX library): 
![Screen Shot 2021-11-19 at 1 33 01 PM](https://user-images.githubusercontent.com/23005868/142799847-955b0f4a-a3af-41c9-a50d-7eeabf7272ec.png)

However, I tend to see the following (using pyEX): 

![Screen Shot 2021-11-19 at 1 26 16 PM](https://user-images.githubusercontent.com/23005868/142799790-1661cad2-4a3b-4fbd-99f8-aaaf10458a9b.png)

**ENV**
 - Tested on Ubuntu 18.04, MacOS Big Sur
 - Tested on Python 3.9 and Python 3.8
 - `intradayDF` and `chartDF` methods (using both `1d` and `dynamic` intervals)
 - Tested Tickers: AAPL, MU, MSFT (all stocks that should have enough volume to have minute price changes)
 - This is all running v0.5.0 (latest as of writing)

**Comment by timkpaine** [comment]
`chart` by default [caches your data locally to avoid excess charges](https://github.com/iexcloud/temporal-cache), by default it expires at 4am EST daily: https://github.com/iexcloud/pyEX/blob/main/pyEX/stocks/chart.py#L26

`intraday` does not cache: https://github.com/iexcloud/pyEX/blob/main/pyEX/stocks/intraday.py#L22

First step in debugging would be to set the env var `PYEX_NOCACHE` and try your test again to see

**Comment by carterjfulcher** [comment]
Ah that's a handy library. Tested again with `PYEX_NOCACHE` and everything worked as I originally excepted. I will close this issue now but it would be ideal if this was made more apparent. Thanks!

**Comment by timkpaine** [comment]
Chart and intraday are a little clunky, but [intraday](https://iexcloud.io/docs/api/#intraday-prices) should get you what you need and for all other queries (like historical intraday queries) the caching will make sure you don't even spend the extra credits for cloud cache/api usage.
